#!/usr/bin/env python3
"""embed-app.py - turn an OS/Two .exe into a C header for the kernel RamFS.

Usage:
    python3 embed-app.py examples/hello.exe > hello_bin.h

Then in kernel.c, next to the other built-in programs:
    #include "hello_bin.h"
    ramfs_write("hello.exe", hello_bin, hello_bin_len);

Rebuild the kernel; the program appears in the shell and runs with:
    exec hello.exe
"""
import sys, os

if len(sys.argv) != 2:
    sys.exit("usage: embed-app.py <app.exe>")

path = sys.argv[1]
data = open(path, "rb").read()
sym = os.path.splitext(os.path.basename(path))[0].replace("-", "_") + "_bin"

out = sys.stdout
out.write("// Generated by sdk/embed-app.py from %s\n" % os.path.basename(path))
out.write("static const unsigned char %s[] = {\n" % sym)
for i in range(0, len(data), 12):
    out.write("    " + ", ".join("0x%02x" % b for b in data[i:i+12]) + ",\n")
out.write("};\n")
out.write("static const unsigned int %s_len = %d;\n" % (sym, len(data)))
